### ISSUE TITLE
Problem with package on PLESK platform

### ISSUE THREAD

**Issue by fsasvari** [srmklive/laravel-paypal#208]
First, thanks you this package, it is absolutely great ;)

But I'm having a problem with it, on server. Locally it works fine.

Server is on PLESK platform and my hosting company says it cannot update OpenSSL to v2 because of PLESK limitation.

I'm having following error on server:

    Use of undefined constant CURL_SSLVERSION_TLSv1_2 - assumed 'CURL_SSLVERSION_TLSv1_2'

Any suggestions what to do ? Website is on http, maybe this is a problem ?

    cURL Information 7.60.0
    SSL Version | OpenSSL/1.0.1e
    OpenSSL Library Version | OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by srmklive** [comment]
You need to have the OpenSSL version updated on the server.

**Comment by jellytoo** [comment]
The hosting operator sysadmin (me) suggested a workaround: use integer value instead of nonexisting symbolic constant in older php curl extension.  No need to upgrade anything.

-bash-4.1$ diff -u ./src/Traits/PayPalHttpClient.php.orig ./src/Traits/PayPalHttpClient.php
--- ./src/Traits/PayPalHttpClient.php.orig      2018-06-13 14:46:57.272085438 +0200
+++ ./src/Traits/PayPalHttpClient.php   2018-06-13 14:46:34.807084442 +0200
@@ -29,7 +29,7 @@
     protected function setHttpClientConfiguration()
     {
         $this->httpClientConfig = [
-            CURLOPT_SSLVERSION     => CURL_SSLVERSION_TLSv1_2,
+            CURLOPT_SSLVERSION     => 6,
             CURLOPT_SSL_VERIFYPEER => $this->validateSSL,
         ];
