### ISSUE TITLE
Relationship between IPN "recurring_payment" and subcription

### ISSUE THREAD

**Issue by joanebrown** [srmklive/laravel-paypal#280]
Thanks to this library I am able to create subscriptions; but, every month, I have to be able to know if the user who created the subscription issues a payment (IPN) to be able to generate an invoice ...

How can I know which sub-subscription an IPN notification of type "recurring_payment" belongs to in order to generate a new invoice?

How to know to which subscription an IPN "recurring_payment" notification belongs?

Can someone tell me how to proceed in these cases? Maybe you are posing it in an erratic way

![image](https://user-images.githubusercontent.com/12473135/59144253-65c59e00-89d5-11e9-80fa-aced3d686e07.png)

**Comment by srmklive** [comment]
IPN does return a recurring payment id. You may need to parse IPN data for your own requirements.

**Comment by joanebrown** [comment]
@srmklive Hi! I see the `recurring_payment_id` in the IPN requests but.. When I create the subscription with `createRecurringPaymentsProfile()` where is the recurring payment?

Thank you!

**Comment by 4unkur** [comment]
@joanebrown were you able to solve the problem? I have the same issue. I need to somehow identify the subscription that is stored in my database when IPN is received.
Also, in the expressCheckout I sent invoice_id value to identify the subscription when user is returned from payment page, but that invoice_id value is missing in IPN data

@srmklive any idea?

The problem is: we are receiving IPN data and after that, we should update payment status, subscription status, etc, etc. The question is: how we can identify which subscription in the db to update?
