### ISSUE TITLE
Undefined index: payKey

### ISSUE THREAD

**Issue by karan-bacancy** [srmklive/laravel-paypal#333]
Hello @srmklive

       $this->provider = new AdaptivePayments();

        $data = [
            'receivers'  => [
                [
                    'email'   => 'sb-abc@business.example.com',
                    'amount'  => 100,
                    'primary' => true,
                ],
                [
                    'email'   => 'sb-xyz@business.example.com',
                    'amount'  => 10,
                    'primary' => false
                ],
            ],
            'payer'      => 'EACHRECEIVER', // (Optional) Describes who pays PayPal fees. Allowed values are: 'SENDER', 'PRIMARYRECEIVER', 'EACHRECEIVER' (Default), 'SECONDARYONLY'
            'return_url' => url('payment/success'),
            'cancel_url' => url('payment/cancel'),
        ];
     $response = $this->provider->createPayRequest($data);
     $redirect_url = $this->provider->getRedirectUrl('approved', $response['payKey']);
I have put this code on my local for adaptive payment but it's give me error like :: Undefined index: payKey. It's not creating response from createPayRequest.

My Project PHP version : 7.3.5 Larave Version :: ^6.2 "srmklive/paypal": "^1.7",

Also on success function how we can get success adaptive payment data..?

Please let me know solution asasp as I have stuck with problem

![image](https://user-images.githubusercontent.com/59202530/78531994-1a9e3680-7804-11ea-9955-c8615fc1b8d4.png)

Thanks
karan shah

**Comment by karan-bacancy** [comment]
Hello @srmklive  @dblencowe @drbyte 

Please give me solution ASAP

**Comment by drbyte** [comment]
@karan-bacancy I don't know why you've tagged me into this discussion.

But in #331 you were already given good advice: dump out the response.
Your application is blindly assuming that a good response will always occur, and you're not accounting for possible failures. You should always test whether `$response` is good before assuming things about it, such as throwing an exception if the response is bad.
Possible failures include that you've set it to use production credentials but have supplied sandbox credentials. Or your PC firewall is blocking guzzle calls. Or errors directly from PayPal.
But since you're not testing for any errors, it's unsurprising that your application is failing.

You were advised to check the actual response. Something like `dd($response)` will give you clues such as errors or other messages about what is wrong. 

It's unfair to open multiple issues in this package blaming them for having a bug, and ignoring the advice given when asking for help.

**Comment by karan-bacancy** [comment]
Hello @drbyte 

I have resolved my issue 

Thanks
