### ISSUE TITLE
paymentID not returned

### ISSUE THREAD

**Issue by awillys** [srmklive/laravel-paypal#556]
Hi there,
We're implementing this package v3 and just came across an issue for our set up.
Or code relies on the paymentID being returned by Paypal but it seems this is not the case here.
When the payment is approved by the user on Paypal and the user is redirected to our website the return url includes the cart_id, the token and the PayerID
e.g.: https://testdomain.localhost/checkout/paypal/approved?cart_id=369&token=6AB26310792666643&PayerID=CZX49JFWXDB68

**is it possible to have the paymentID included in that URL?**
we are currently relying on its availability to validate the payment and match it to the transaction.

Thank you
Antonio

**Comment by Meera9** [comment]
Hello, 

How can i get the order detail by v3.0  without order_id but using payerid and token ? is that any way possible?

i need the above description because of I  have to fetch the payment id before I have authorized the order detail and fetch the payment id and using that payment Id i can easily get a response from the payment is there any way possible?

**Comment by srmklive** [comment]
You need to use PayPal JS library for this. The package caters to the backend not the frontend.
