### ISSUE TITLE
enable-funding

### ISSUE THREAD

**Issue by biscofil** [srmklive/laravel-paypal#620]
Hello all,

I looked around but apparently the enable-funding feature (https://developer.paypal.com/sdk/js/configuration/#enable-funding) is not available through this library. Am I wrong? 

Any guidance on how to add it? I can open a PR for it

Many thanks

**Comment by otnansirk** [comment]
I think you can just start adding this feature and run tests and then create a PR.
Repo owner will start reviewing your PR

Because there is no specific guide on how to add new features.

Ref : https://github.com/srmklive/laravel-paypal?tab=readme-ov-file#support

I'm sure you won't have any trouble reading how the code works. after looking at the code structure.

**Comment by srmklive** [comment]
Please go ahead and add the PR.

**Comment by otnansirk** [comment]
Hi @biscofil,
Are you currently working on this issue ?

**Comment by biscofil** [comment]
Hi all, nope sorry
